#!/usr/bin/env python
#
# A simple python fontforge script to show all the author metadata
# and to check for best practises when filling in the various fields.
# you need a recent version of fontforge.
# The script works for all font formats fontforge supports.
#
# See the various resources and websites of the open font community:
# http://planet.open-fonts.org
# http://utilities.open-fonts.org
#
# Thanks to Martin Hosken
# http://www.sil.org/~hosken/
#
# Copyright (c) 2010, Nicolas Spalinger
#
# Released under the MIT license.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


import fontforge, sys
required_version = "20100212"

if fontforge.version() < required_version:
    print ("Your version of FontForge is too old - %s or newer is required" % (required_version))

def main ():
    for f in sys.argv[1:]:
        font = fontforge.open(f)

    print (" ")
    print ("File: " + font.path)
    print ("Fontname: " + font.fontname)
    print ("Weight: " + font.weight)
    print ("Family name: ")
    print (font.familyname)
    print ("Full name: ")
    print (font.fullname) 

    names = {}
    for n in font.sfnt_names :
        if n[0] == "English (US)" :
            names[n[1]] = n[2]
    print ("PostScript name: ")
    print names.get ('PostScriptName')
    print ("Full name: ")
    print names.get ('Fullname')
    print ("UniqueID: ")
    print names.get ('UniqueID')
    print ("Subfamily:  ")
    print names.get ('SubFamily')
    print ("Preferred family: ")
    print names.get ('Preferred Family')
    print ("Compatible Full: ")
    print names.get ('Compatible Full')

if __name__ == '__main__':
    main()
